#!/bin/sh

set -e

. /usr/share/debconf/confmodule

## CHANGE ME
echo user:pass | /usr/sbin/chpasswd

case "$1" in
	configure)
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
